# Generated by Django 5.1 on 2024-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0002_club_user_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylist',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='moneylist',
            name='expense',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moneylist',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
