# Generated by Django 5.1 on 2024-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0003_moneylist_category_moneylist_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylist',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='date published'),
        ),
    ]
