# Generated by Django 5.1 on 2024-08-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0004_moneylist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberdues',
            field=models.BooleanField(default=False),
        ),
    ]
