# Generated by Django 5.1 on 2024-08-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0005_alter_member_memberdues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='user',
        ),
    ]
