# Generated by Django 5.1 on 2024-08-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0006_alter_club_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
