# Generated by Django 5.1 on 2024-08-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0009_remove_moneylist_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneylist',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
