# Generated by Django 5.1 on 2024-08-23 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundi', '0007_club_user'),
        ('fundi', '0010_moneylist_budget'),
    ]

    operations = [
    ]
